"""Static instruction scanner: find rigid instructions a strong model will obey into a silent error.

Lesson from the order demo: the model noticed the cancelled order, then summed it anyway,
"because the skill definition says so" (its own words, translated). Missing instructions a strong model fills in by itself; wrong or rigid
ones it follows. This scanner reads SKILL.md, no model call, and says which anomaly tests to run.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

# The patterns match Turkish and English instruction text: they are data, not interface text.
RULES = [
    ("unconditional_aggregate", r"(?i)\b(topla|toplam(ı|ını)?|say|hepsini|tümünü|tamamını|sum|count|all)\b",
     "Unconditional sum or count: cancelled, duplicate or mixed-unit records can be included",
     ["cancelled_record", "duplicate_record", "mixed_units"]),
    ("rigid_format", r"(?i)(tam olarak|birebir|şu biçimde|şu formatta|son satır|exactly|always output)",
     "Rigid output format: can force a 'normal' line even when the data is broken",
     ["stale_date", "missing_field"]),
    ("absolute_rule", r"(?i)\b(her zaman|her koşulda|asla|kesinlikle|mutlaka|daima|never|always)\b",
     "Absolute rule: applied in the exceptional case too", []),
    ("no_human_handoff", r"(?i)(soru sorma|onay isteme|kullanıcıya sorma|don't ask|without asking)",
     "No handoff to a human: carries on even when unsure", ["missing_field"]),
]
GUARD = re.compile(  # the same line puts a condition on the instruction
    r"(?i)(kontrol|değilse|hariç|yalnız(ca)?|eğer|\bise\b|durumda|olmayan|dışında|\bif\b|unless|except)"
)
TEMPLATE = re.compile(r"^\s*[-*]?\s*`[^`]*`\s*$")  # a bare output template, not an instruction
ESCAPE = re.compile(
    r"(?i)(eksik|hatalı|bozuk|uyuşm|tutmazsa|gelmezse|yoksa|hata verirse|emin değilsen|"
    r"iptal|farklı(ysa)?|değilse|alınamadı|dur\b|durdur|sor\b|if .{0,30}(missing|invalid|fails))"
)


@dataclass
class Finding:
    line: int
    rule: str
    text: str
    risk: str
    tests: list[str]
    guarded: bool = False


def scan(skill_md: str) -> tuple[list[Finding], bool]:
    """(findings, has_escape): has_escape is False when nothing says what to do on bad data."""
    body = skill_md.split("---", 2)[-1] if skill_md.startswith("---") else skill_md
    offset = skill_md.count("\n", 0, len(skill_md) - len(body))
    findings: list[Finding] = []
    for i, line in enumerate(body.splitlines(), start=offset + 1):
        if TEMPLATE.match(line):
            continue
        for rule, pattern, risk, tests in RULES:
            if re.search(pattern, line):
                findings.append(Finding(i, rule, line.strip(), risk, tests, GUARD.search(line) is not None))
    return findings, ESCAPE.search(body) is not None


def report(name: str, skill_md: str) -> str:
    findings, escape = scan(skill_md)
    lines = [f"# Instruction scan: {name}", ""]
    if not escape:
        lines += [
            (
                "⚠️ **No escape route:** the skill never says what to do when data is missing "
                "or broken. Together with rigid instructions, this is the most common path to a "
                "silent wrong."
            ),
            "",
        ]
    if not findings:
        lines.append("No risky instruction pattern found.")
        return "\n".join(lines) + "\n"
    open_ = [f for f in findings if not f.guarded]
    lines += [
        (
            f"{len(findings)} risky patterns, **{len(open_)} unconditional** (no condition on the "
            "same line). The scanner looks at words and does not weigh meaning: the suggested "
            "tests give the final verdict."
        ),
        "",
        "| Line | Pattern | Has a condition | Instruction | Risk |",
        "|---|---|---|---|---|",
    ]
    lines += [
        f"| {f.line} | {f.rule} | {'yes' if f.guarded else '**no**'} | {f.text[:70]} | {f.risk} |"
        for f in findings
    ]
    tests = sorted({t for f in findings for t in f.tests})
    if tests:
        lines += ["", "**Suggested anomaly tests to run:** " + ", ".join(f"`{t}`" for t in tests),
                  "", "Generated by adding `auto_faults: [data_anomaly]` to the scenario."]
    return "\n".join(lines) + "\n"
